server:
  port: 9009
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://172.16.1.18:3306/banma_dev?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&zeroDateTimeBehavior=convertToNull&useSSL=true
      username: root
      password: 123456
  application:
      name: schedule

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.schedule.domain
  mapperLocations: classpath*:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#RestTemplate配置
client:
  root:
    uri: http://172.16.1.14:9011
  connect:
    timeout: 5000
  read:
    timeout: 5000
  report:
        root:
          uri: http://172.16.1.14:9001
        connect:
          timeout: 5000
        read:
          timeout: 5000