server:
  port: 10001
  tomcat:
    uri-encoding: UTF-8
# datasource
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/guardian?characterEncoding=utf8
      username: root
      password: 123456
  application:
      name: schedule

#mybatis配置
mybatis:
  typeAliasesPackage: com.banmatrip.schedule.domain
  mapperLocations: classpath*:mapper/*.xml
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  configuration.call-setters-on-nulls: true

#RestTemplate配置
client:
  root:
    uri: http://172.16.40.22:8080
  connect:
    timeout: 5000
  read:
    timeout: 5000
  report:
        root:
          uri: http://172.16.40.22:9001
        connect:
          timeout: 5000
        read:
          timeout: 5000